### ISSUE TITLE
Please comment on this issue to be added as a collaborator.

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/dev-oct-25-emea#2]
Tell us -- where are you visiting us from today?

**Comment by stoe** [comment]
ahoi

**Comment by stoe** [comment]
Ahoi, everyone.

![](https://upload.wikimedia.org/wikipedia/de/thumb/3/3f/Ahoj_logo.svg/220px-Ahoj_logo.svg.png)

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by els2171** [comment]
NYC!

**Comment by bazfire** [comment]
Good Start!

**Comment by LaurenceRobert** [comment]
FFM

**Comment by LemonVulpes** [comment]
Howdy

**Comment by tanayx** [comment]
India

**Comment by ErikHendriks** [comment]
Hello, Enjoy!

**Comment by gjICBC** [comment]
hi

**Comment by pbharath** [comment]
San Jose

**Comment by gedatamas** [comment]
SWH

**Comment by AlexCFurtuna** [comment]
Hello everyone

**Comment by lucasmeyer1** [comment]
Amazing :)

**Comment by uidv4456** [comment]
Regensburg

**Comment by herbert-hofmann** [comment]
hi

**Comment by erikalarsson** [comment]
Södertälje, Sweden

**Comment by aguieb** [comment]
go cubs

**Comment by bulislaw** [comment]
Cambridge

**Comment by zemunk** [comment]
Hi

**Comment by mflorys** [comment]
Hello :) :+1:

**Comment by PaulTafur** [comment]
IL

**Comment by teintoo** [comment]
Markham, Ontario, Canada 👍

**Comment by githubteacher** [comment]
🚶 🏡  Hi y'all.

**Comment by rherzfeld** [comment]
Germany!

**Comment by luke227** [comment]
Toronto

**Comment by ashok-rao** [comment]
Hello from Cambridge, UK :-)

**Comment by sanjaybharadwaj** [comment]
Hello!!

**Comment by AndrewWL** [comment]
Hi from Toronto

**Comment by sunit1** [comment]
HI 👍

**Comment by venkataraman1985** [comment]
Hello all

**Comment by ErikHendriks** [comment]
Hello

**Comment by anujshah1003** [comment]
bengaluru

**Comment by handiandi** [comment]
Denmark

**Comment by aguieb** [comment]
test

**Comment by sakshaya** [comment]
looks good

**Comment by uidv4456** [comment]
Hi

**Comment by bbogusla** [comment]
Grenoble, France

**Comment by ToWi87** [comment]
hey

**Comment by rsm23** [comment]
`Hello Every One`
#Annaba, Algeria

**Comment by juanwolf** [comment]
# HELLO

**Comment by lucasmeyer1** [comment]
Amazing :)

**Comment by enrcor01** [comment]
Hi

**Comment by shashank7289** [comment]
Hi All

**Comment by danieltendaj** [comment]
Hello

**Comment by lucasmeyer1** [comment]
👍

**Comment by rikpel-arm** [comment]
Hi from Oulu, Finland!

**Comment by sakshaya** [comment]
Hi from bangalore

**Comment by tigdlo** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @tanayx, @ErikHendriks, @gjICBC, @pbharath, @gedatamas, @AlexCFurtuna, @lucasmeyer1, @uidv4456, @herbert-hofmann, @erikalarsson, @aguieb, @bulislaw, @zemunk, @mflorys, @PaulTafur, @teintoo, @rherzfeld, @luke227, @ashok-rao, @sanjaybharadwaj, @AndrewWL, @sunit1, @venkataraman1985, @ErikHendriks, @anujshah1003, @handiandi, @aguieb, @sakshaya, @uidv4456, @bbogusla, @ToWi87, @rsm23, @juanwolf, @lucasmeyer1, @enrcor01, @shashank7289, @danieltendaj, @lucasmeyer1, @rikpel-arm, and @sakshaya are now  repository collaborators. :balloon:

**Comment by mflorys** [comment]
Hello

**Comment by fabiosony** [comment]
!!

**Comment by githubteacher** [comment]
:tada: @tigdlo and @fabiosony are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
:tada: @els2171, @bazfire, @LaurenceRobert, @LemonVulpes, @tanayx, @ErikHendriks, @gjICBC, @pbharath, @gedatamas, @AlexCFurtuna, @lucasmeyer1, @uidv4456, @herbert-hofmann, @erikalarsson, @aguieb, @bulislaw, @zemunk, @mflorys, @PaulTafur, @teintoo, @rherzfeld, @luke227, @ashok-rao, @sanjaybharadwaj, @AndrewWL, @sunit1, @venkataraman1985, @ErikHendriks, @anujshah1003, @handiandi, @aguieb, @sakshaya, @uidv4456, @bbogusla, @ToWi87, @rsm23, @juanwolf, @lucasmeyer1, @enrcor01, @shashank7289, @danieltendaj, @lucasmeyer1, and @rikpel-arm are now  repository collaborators. :balloon:

**Comment by Jamie-Owen** [comment]
`console.log('hello world!');`

**Comment by mhmreddy** [comment]
Nice

**Comment by githubteacher** [comment]
:tada: @Jamie-Owen and @mhmreddy are now  repository collaborators. :balloon:

**Comment by manbuysdog** [comment]
London

**Comment by githubteacher** [comment]
:tada: @manbuysdog and @ZenMC are now  repository collaborators. :balloon:

**Comment by mokarbeen** [comment]
Hello

**Comment by alex-smith-excelian** [comment]
Yo

**Comment by alanblyth** [comment]
Oxfordshire

**Comment by githubteacher** [comment]
:tada: @mokarbeen, @alex-smith-excelian, and @alanblyth are now  repository collaborators. :balloon:

**Comment by aguieb** [comment]
test again

**Comment by rsm23** [comment]
@crichID Thank you so much for the `badge`

**Comment by anngoc** [comment]
Hi

**Comment by githubteacher** [comment]
@crichID what do you think so far about our class?

**Comment by crichID** [comment]
@githubteacher it is looking awesome so far!

**Comment by manbuysdog** [comment]
@tigdlo hi!

**Comment by githubteacher** [comment]
:tada: @anngoc is now a repository collaborator. :balloon:

**Comment by rherzfeld** [comment]
#3

**Comment by julietjake** [comment]
hi!

**Comment by githubteacher** [comment]
:tada: @julietjake is now a repository collaborator. :balloon:

**Comment by pmootyen** [comment]
Please add me :)

**Comment by githubteacher** [comment]
:tada: @pmootyen is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
@crichID I'm dropping out of this issue for some PTO over the next minutes.

**Comment by fabiosony** [comment]
@githubteacher is ignoring this thread

**Comment by crichID** [comment]
@githubteacher you don't get time off

**Comment by fredlee12001** [comment]
Add me.

**Comment by lrjbrual** [comment]
Add me.

**Comment by githubteacher** [comment]
:tada: @fredlee12001 and @lrjbrual are now  repository collaborators. :balloon:

**Comment by AndrewWL** [comment]
I got email

**Comment by swinton** [comment]
:Wave: Sorry I'm late 😞

**Comment by githubteacher** [comment]
:tada: @swinton is now a repository collaborator. :balloon:

**Comment by stoe** [comment]
:wave:

**Comment by stoe** [comment]
:wave:

**Comment by githubstudent** [comment]
holla

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @swinton is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:
