### ISSUE TITLE
LR -  Practice GitHub Flow

### ISSUE THREAD

**Issue by LaurenceRobert** [githubteacher/dev-oct-25-emea#26]
Checklist
- [x] Create an Issue
- [ ] Create a Branch
- [ ] Make commits
- [ ] Open a pull request
- [ ] Collaborate!
- [ ] Merge pull request
- [ ] Have a great time!

**Comment by AndrewWL** [comment]
[ ] Create an Issue
[ ] Create a Branch
[ ] Make commits
[ ] Open a pull request
[ ] Collaborate!
[ ] Merge pull request
[ ] Have a great time!
